inherit_gem:
  gc_ruboconfig: rubocop.yml

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable

Gemspec/RequiredRubyVersion:
  Enabled: false

Naming/FileName:
  Exclude:
    - lib/activerecord-safer_migrations.rb

Style/GlobalVars:
  Exclude:
    - "spec/active_record/safer_migrations/migration_spec.rb"
