version: 2.1

jobs:
  test:
    docker:
      - image: circleci/ruby:<< parameters.ruby-version >>
      - image: postgres:11.3
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: safer_migrations_test
          POSTGRES_PASSWORD: ""
          POSTGRES_HOST_AUTH_METHOD: trust
    environment:
      DATABASE_URL: postgres://postgres@localhost/safer_migrations_test
      ACTIVERECORD_VERSION: << parameters.activerecord-version >>
    parameters:
      ruby-version:
        type: string
      activerecord-version:
        type: string
    steps:
      - checkout
      - restore_cache:
          keys:
            - bundle-v1-<< parameters.ruby-version >>-{{ checksum "activerecord-safer_migrations.gemspec" }}
            - bundle-v1-<< parameters.ruby-version >>-
      - run:
          name: Install dependencies
          command: bundle install --clean --no-cache --path vendor/bundle --jobs=4 --retry=3
      - save_cache:
          key: bundle-v1-<< parameters.ruby-version >>-{{ checksum "activerecord-safer_migrations.gemspec" }}
          paths:
            - vendor/bundle
      - run:
          name: Run tests
          command: bundle exec rspec
      - run:
          name: Run rubocop
          command: bundle exec rubocop --parallel --extra-details --display-style-guide

workflows:
  default:
    jobs:
      - test:
          name: "Ruby << matrix.ruby-version >> : ActiveRecord << matrix.activerecord-version >>"
          matrix:
            parameters:
              activerecord-version:
                - 5.2.4.4
                - 6.0.3.3
              ruby-version:
                - 2.5.8
                - 2.6.6
                - 2.7.1
                # - 3.0.0-preview1
